### PR TITLE
Add bios change job wait using StateChangeConf method

### LINKED ISSUE #18: Wait for BIOS update job to finish
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description
While updating BIOS setup using this provider I noticed that it created a job on the iDRAC but it did not wait for the job to finish.
IMHO the correct behavior (from TF perspective) it is to wait (sync or async) for the resource configuration to be applied.
The code can be changed to use existing method `WaitForJobToFinish`
### New or Affected Resource(s)

* redfish_bios

### Potential Terraform Configuration

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file.
resource "redfish_bios" "bios" {

  redfish_server {
    endpoint = "https://192.168.8.103:6443"
    ssl_insecure = true
  }
  attributes = {
    "SysProfile" = "PerfOptimized"
  }
  settings_apply_time = "OnReset"
  action_after_apply = "ForceRestart"
  wait_to_finish = true
}

```

### References

* #0000

### PR DESCRIPTION
**Pull request by brutus333**
Fixes #18

Signed-off-by: Virgil Chereches <virgil.chereches@gmail.com>

##### SUMMARY

Closes #18
##### ISSUE TYPE

- Bugfix Pull Request

##### COMPONENT NAME

`redfish_bios`
##### ADDITIONAL INFORMATION

The provider should wait until bios change job has finished and return a failure if the job fails.
The right way to implement this wait is by using TF SDK StateChangeConf method - other providers such as GCP and AWS ones are using this method whenever the provider should wait after some events during create/update of a resource.

```paste below

```

#### Release note for [CHANGELOG](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md):

```release-note

```

#### Output from acceptance testing:

```
$ make testacc TESTARGS='-run=TestAccXXX'

...
```

#### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

### CODE REVIEW

**Comment by brutus333** [comment]
This is a first attempt to fix the provider - as of now the code does not deal with error conditions like loosing access to iDRAC, job hanging and other exceptions that might occur.
I propose to open a different issue to deal with that part.

**Comment by grantcurell** [comment]
@brutus333 I have to know - did you go to Ohio State? Or is the name unrelated and this question makes no sense?

**Comment by brutus333** [comment]
> @brutus333 I have to know - did you go to Ohio State? Or is the name unrelated and this question makes no sense?

@grantcurell : no, not at all. Is this a kind of joke?

**Comment by anupamaloke** [comment]
@brutus333 my sincere apologies for the delay in review. I will be taking a look and provide comments, if any.

**Comment by grantcurell** [comment]
> > @brutus333 I have to know - did you go to Ohio State? Or is the name unrelated and this question makes no sense?
> 
> @grantcurell : no, not at all. Is this a kind of joke?

Not a joke hahaha sorry I added to the confusion. In my area of the US, Brutus is an uncommon name and usually whenever you see it, it refers to the mascot of a large school nearby. It is particularly popular in user names

**Review by anupamaloke — APPROVED** [review]
LGTM

**Pull request merged**
