### PR TITLE
SimpleUpdate resource implemented

### LINKED ISSUE #7: NEW FEATURE: Implement SimpleUpdate on the provider
- [ ] - Write CRUD Operations that carries out the expected behavior ( Update the firmware of the machine)
- [ ] - Create unit tests for the code written

### PR DESCRIPTION
**Pull request by mikeletux**
##### SUMMARY

This PR implements basic functionality for 

Closes #7 

##### ISSUE TYPE

- New Module Pull Request

##### COMPONENT NAME

redfish_simple_update

##### ADDITIONAL INFORMATION

This resource adds basic functionality for simpleUpdate. At the moment only supports HTTP as *transfer_protocol*, but we are open to add more in the future as its needed. We stated for that one because it's the one dell implements in it's redfish implementation.
An example .tf file that could be used can be shown below:

```paste below
terraform {
    required_providers {
        redfish = {
            source = "dell/redfish"
        }
    }
}

resource "redfish_simple_update" "update" {
    for_each = var.rack1

    redfish_server {
        user = each.value.user
        password = each.value.password
        endpoint = each.value.endpoint
        ssl_insecure = each.value.ssl_insecure
    } 
    
    transfer_protocol = "HTTP"
    target_firmware_image = "/home/mikeletux/Downloads/BIOS_FXC54_WN64_1.15.0.EXE"
    reset_type = "ForceRestart"
    // reset_timeout = 120 // If not set, by default will be 120s
    // simple_update_job_timeout = 1200 // If not set, by default will be 1200s
}
```

#### Release note for [CHANGELOG](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md):

```release-note
 - Added redfish_simple_update resource
```

#### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

### CODE REVIEW

**Comment by mikeletux** [comment]
@grantcurell @sunilvijendra if you want to review, feel free as well :smile:

**Comment by anupamaloke** [comment]
Adding @grantcurell, @sunilvijendra for their comments as well.

**Comment by grantcurell** [comment]
image

Not sure why yet, but when I run the code I get this.

**Comment by mikeletux** [comment]
> 
> 
> image
> 
> Not sure why yet, but when I run the code I get this.
> 
> Edit: Never mind, I think I know why.

Also make sure you compile it using the master branch from gofish

**Comment by grantcurell** [comment]
image

Regarding the above, yes, I'm an idiot and totally forgot to recompile (I need to set up my IDE to make it do that for me).

That said, it does look like there's an undefined function

**Comment by grantcurell** [comment]
I see the definition https://github.com/stmcginnis/gofish/blob/dd98a92c95b02929c47160ec738eb394c5bd5f73/client.go#L289

trying to figure out what the problem is now

**Comment by grantcurell** [comment]
I found the problem - that function, , does not exist in GoFish's client interface:

image

When I run `go mod vendor` I do not get the same version as what's at: https://github.com/stmcginnis/gofish/blob/main/common/types.go

**Comment by grantcurell** [comment]
@mikeletux suggest updating go.mod to:

```
module github.com/dell/terraform-provider-redfish

go 1.14

require (
	github.com/hashicorp/go-multierror v1.0.0 // indirect
	github.com/hashicorp/terraform-plugin-sdk/v2 v2.4.4
	github.com/stmcginnis/gofish v0.9.1-0.20210424150652-dd98a92c95b0
)
```

until gofish release is patched. Other than that it ran fine for me.

**Comment by mikeletux** [comment]
> 
> 
> @mikeletux suggest updating go.mod to:
> 
> ```
> module github.com/dell/terraform-provider-redfish
> 
> go 1.14
> 
> require (
> 	github.com/hashicorp/go-multierror v1.0.0 // indirect
> 	github.com/hashicorp/terraform-plugin-sdk/v2 v2.4.4
> 	github.com/stmcginnis/gofish v0.9.1-0.20210424150652-dd98a92c95b0
> )
> ```
> 
> until gofish release is patched. Other than that it ran fine for me.

Grant,

We can tell Sean from Gofish to tag the master branch as it is currently as v0.10.0, that will make the trick.
Glad also that you consider it's ok 😄

**Review by anupamaloke — APPROVED** [review]
LGTM. Approved

**Pull request merged**
