### PR TITLE
Initial docs

### PR DESCRIPTION
**Pull request by prajwalpatil25**
Initial docs for Redfish

### CODE REVIEW

**Review by Sakshi-dell — APPROVED** [review]

**Comment by rounak-adhikary** [comment]
The examples folder is not following the correct pattern, which is why the generated documenatation has no examples.
Please check https://github.com/dell/terraform-provider-powerflex/tree/main/examples as an example.

**Comment by rounak-adhikary** [comment]
The generated documentation also does not have copyright headers. This can be rectified by creating 3 files:
1. https://github.com/dell/terraform-provider-powerflex/blob/main/templates/resources.md.tmpl
2. https://github.com/dell/terraform-provider-powerflex/blob/main/templates/index.md.tmpl
3. https://github.com/dell/terraform-provider-powerflex/blob/main/templates/data-sources.md.tmpl

**Comment by prajwalpatil25** [comment]
Hi @rounak-adhikary thanks for the comments. we'll be customizing docs in upcoming PRs. These PR is just to have .md files in place with whatever schema details we have added.

**Review by rounak-adhikary — APPROVED** [review]
in that case, LGTM

**Pull request merged**
